apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: helloworld
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
          image: gcr.io/fine-jetty-280616/github.com/fernandobastos/gke-hello
          imagePullPolicy: Always
          name: hello-app
          ports:
            - containerPort: 8080
              protocol: TCP
