apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  clusterIP: 10.39.251.116
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31747
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello
  sessionAffinity: None
  type: LoadBalancer
